n1=input('Enter your name 1: ')
n2=input('Enter your name 2: ')
n3=input('Enter your name 3: ')
n4=input('Enter your name 4: ')
n5=input('Enter your name 5: ')
n6=input('Enter your name 6: ')
n7=input('Enter your name 7: ')
n8=input('Enter your name 8: ')
n9=input('Enter your name 9: ')
n10=input('Enter your name 10: ')
t=input('Enter your word: ')

n1=n1.capitalize()
n2=n2.capitalize()
n3=n3.capitalize()
n4=n4.capitalize()
n5=n5.capitalize()
n6=n6.capitalize()
n7=n7.capitalize()
n8=n8.capitalize()
n9=n9.capitalize()
n10=n10.capitalize()

a=n1.count(t) + n2.count(t) + n3.count(t) + n4.count(t) + n5.count(t) + n6.count(t) + n7.count(t) + n8.count(t) + n9.count(t) + n10.count(t)
t=t.title()
b=n1.count(t) + n2.count(t) + n4.count(t) + n3.count(t) + n5.count(t) + n6.count(t) + n7.count(t) + n8.count(t) + n9.count(t) + n10.count(t)
a += b
print(n1,n2,n3,n4,n5,n6,n7,n8,n9,n10,a)